# Generated by Django 3.2.13 on 2022-07-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SightsingingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.CharField(max_length=50)),
                ('part_name', models.CharField(max_length=20, null=True)),
                ('part_rank', models.CharField(max_length=5)),
                ('audio_path', models.TextField()),
                ('pic_path', models.TextField()),
                ('xml_path', models.TextField()),
                ('audio_size', models.FloatField()),
            ],
        ),
    ]
