# Generated by Django 3.2.13 on 2022-07-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0002_sightsingingquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sightsingingquestion',
            name='lesson_No',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
