# Generated by Django 3.2.13 on 2022-07-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0004_auto_20220713_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.CharField(max_length=50)),
                ('audio_name', models.TextField(null=True)),
                ('audio_player', models.TextField()),
                ('audio_instrument', models.TextField()),
                ('audio_nation', models.TextField(null=True)),
                ('audio_skill', models.TextField(null=True)),
                ('audio_size', models.FloatField()),
            ],
        ),
    ]
