# Generated by Django 3.2.13 on 2022-07-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0005_audiodetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicequestion',
            name='lesson_No',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
