# Generated by Django 3.2.13 on 2022-07-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0006_choicequestion_lesson_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicequestion',
            name='L_ques_score',
            field=models.IntegerField(default=0),
        ),
    ]
