# Generated by Django 3.2.13 on 2022-07-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0007_choicequestion_l_ques_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicequestion',
            name='part_name',
            field=models.CharField(default='音阶', max_length=20),
        ),
    ]
