# Generated by Django 3.2.13 on 2022-07-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0008_choicequestion_part_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicequestion',
            name='part_name',
            field=models.CharField(max_length=20),
        ),
    ]
