# Generated by Django 3.2.13 on 2022-08-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0009_alter_choicequestion_part_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.CharField(max_length=50)),
                ('choice_ans', models.CharField(max_length=5)),
                ('extra_info', models.TextField(null=True)),
                ('L_ques_txt', models.TextField()),
                ('L_ques_score', models.IntegerField(default=0)),
                ('part_name', models.CharField(max_length=20)),
                ('ques_txt', models.TextField()),
                ('ques_audio_path', models.TextField()),
                ('ques_xml_path', models.TextField(null=True)),
                ('ques_pic_path', models.TextField(null=True)),
                ('choice_rank', models.CharField(max_length=5)),
                ('lesson_No', models.CharField(max_length=5, null=True)),
                ('score', models.IntegerField()),
                ('a_pic_path', models.TextField()),
                ('a_xml_path', models.TextField()),
                ('a_audio_path', models.TextField()),
                ('a_txt', models.TextField(null=True)),
                ('ques_audio_size', models.FloatField()),
            ],
        ),
    ]
