# Generated by Django 3.2.13 on 2024-04-09 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0010_dictationquestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiodetail',
            options={'verbose_name': '音频库', 'verbose_name_plural': '音频库'},
        ),
        migrations.AlterModelOptions(
            name='choicequestion',
            options={'verbose_name': '选择题题库', 'verbose_name_plural': '选择题题库'},
        ),
        migrations.AlterModelOptions(
            name='dictationquestion',
            options={'verbose_name': '听写题题库', 'verbose_name_plural': '听写题题库'},
        ),
        migrations.AlterModelOptions(
            name='sightsingingquestion',
            options={'verbose_name': '视唱题题库', 'verbose_name_plural': '视唱题题库'},
        ),
    ]
