# Generated by Django 3.2.13 on 2024-04-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0011_auto_20240409_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiodetail',
            name='audio_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiodetail',
            name='audio_nation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiodetail',
            name='audio_skill',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='a_txt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='b_txt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='c_txt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='d_txt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='extra_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='lesson_No',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='ques_pic_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='ques_xml_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dictationquestion',
            name='a_txt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dictationquestion',
            name='extra_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dictationquestion',
            name='lesson_No',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='dictationquestion',
            name='ques_pic_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dictationquestion',
            name='ques_xml_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
