# Generated by Django 3.2.13 on 2022-07-09 00:30

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SightsingingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.CharField(max_length=50)),
                ('record_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('audio', models.FileField(upload_to='audio/%Y%m%d')),
                ('vice_audio', models.FileField(null=True, upload_to='audio/%Y%m%d')),
                ('merge_audio', models.FileField(null=True, upload_to='audio/%Y%m%d')),
                ('computer_score', models.IntegerField(null=True)),
                ('teacher_score', models.IntegerField(null=True)),
                ('fluency', models.IntegerField(null=True)),
                ('speed', models.IntegerField(null=True)),
                ('rhythm', models.IntegerField(null=True)),
                ('alignment', models.IntegerField(null=True)),
                ('chord', models.IntegerField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=models.SET(0), related_name='sightsinging_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DictationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.CharField(max_length=50)),
                ('json_field', models.FileField(null=True, upload_to='json/%Y%m%d')),
                ('png_field', models.FileField(null=True, upload_to='png/%Y%m%d')),
                ('computer_score', models.IntegerField(null=True)),
                ('teacher_score', models.IntegerField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=models.SET(0), related_name='dictation_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.CharField(max_length=50)),
                ('record_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('response', models.CharField(max_length=5)),
                ('score', models.IntegerField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=models.SET(0), related_name='choice_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
