# Generated by Django 3.2.13 on 2022-07-09 01:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictationrecord',
            name='json_field',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='dictationrecord',
            name='png_field',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sightsingingrecord',
            name='audio',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='sightsingingrecord',
            name='merge_audio',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sightsingingrecord',
            name='vice_audio',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Png',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(upload_to='png/%Y%m%d')),
                ('part_id', models.CharField(max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=models.SET(0), related_name='png_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Json',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(upload_to='json/%Y%m%d')),
                ('part_id', models.CharField(max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=models.SET(0), related_name='json_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(upload_to='audio/%Y%m%d')),
                ('part_id', models.CharField(max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=models.SET(0), related_name='audio_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
