# Generated by Django 3.2.13 on 2022-07-14 11:40

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homework', '0002_auto_20220709_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictationrecord',
            name='record_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='QuseGroupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_part_id', models.CharField(max_length=50)),
                ('group_title', models.TextField()),
                ('lesson_No', models.CharField(max_length=5)),
                ('state', models.CharField(max_length=5)),
                ('computer_score', models.IntegerField(null=True)),
                ('teacher_score', models.IntegerField(null=True)),
                ('record_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=models.SET(0), related_name='Ques_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
