# Generated by Django 3.2.13 on 2022-07-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_auto_20220714_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qusegrouprecord',
            name='state',
            field=models.IntegerField(),
        ),
    ]
