# Generated by Django 3.2.13 on 2022-07-15 17:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homework', '0005_auto_20220715_1415'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuseGroupRecord',
            new_name='QuesGroupRecord',
        ),
    ]
