# Generated by Django 3.2.13 on 2022-07-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0006_rename_qusegrouprecord_quesgrouprecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sightsingingrecord',
            name='audio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sightsingingrecord',
            name='merge_audio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sightsingingrecord',
            name='vice_audio',
            field=models.TextField(null=True),
        ),
    ]
