# Generated by Django 3.2.13 on 2022-08-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0007_auto_20220719_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictationrecord',
            name='json_field',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dictationrecord',
            name='png_field',
            field=models.TextField(null=True),
        ),
    ]
