# Generated by Django 3.2.13 on 2022-08-21 16:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homework', '0008_auto_20220813_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='sightsingingrecord',
            name='coop_user',
            field=models.ForeignKey(null=True, on_delete=models.SET(0), related_name='sightsinging_coopUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
