# Generated by Django 3.2.13 on 2022-08-21 16:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homework', '0009_sightsingingrecord_coop_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesgrouprecord',
            name='coop_user',
            field=models.ForeignKey(null=True, on_delete=models.SET(0), related_name='Ques_coopUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
