# Generated by Django 3.2.13 on 2022-08-26 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0011_auto_20220826_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sightsingingrecord',
            old_name='quse_type',
            new_name='ques_type',
        ),
    ]
