# Generated by Django 3.2.13 on 2022-11-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0013_quesgrouprecord_record_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sightsingingrecord',
            name='pitch',
            field=models.IntegerField(null=True),
        ),
    ]
