# Generated by Django 3.2.13 on 2024-04-09 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0014_sightsingingrecord_pitch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={'verbose_name': '音频记录表', 'verbose_name_plural': '音频记录表'},
        ),
        migrations.AlterModelOptions(
            name='choicerecord',
            options={'verbose_name': '练耳选择题作业记录表', 'verbose_name_plural': '练耳选择题作业记录表'},
        ),
        migrations.AlterModelOptions(
            name='dictationrecord',
            options={'verbose_name': '练耳听写题作业记录表', 'verbose_name_plural': '练耳听写题作业记录表'},
        ),
        migrations.AlterModelOptions(
            name='json',
            options={'verbose_name': 'json记录表', 'verbose_name_plural': 'json记录表'},
        ),
        migrations.AlterModelOptions(
            name='png',
            options={'verbose_name': '图片记录表', 'verbose_name_plural': '图片记录表'},
        ),
        migrations.AlterModelOptions(
            name='quesgrouprecord',
            options={'verbose_name': '题组记录表', 'verbose_name_plural': '题组记录表'},
        ),
        migrations.AlterModelOptions(
            name='sightsingingrecord',
            options={'verbose_name': '视唱作业记录表', 'verbose_name_plural': '视唱作业记录表'},
        ),
    ]
