# Generated by Django 3.2.13 on 2024-04-16 22:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homework', '0015_auto_20240409_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(0), related_name='audio_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dictationrecord',
            name='computer_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dictationrecord',
            name='json_field',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dictationrecord',
            name='png_field',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dictationrecord',
            name='teacher_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dictationrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(0), related_name='dictation_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='json',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(0), related_name='json_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='png',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(0), related_name='png_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quesgrouprecord',
            name='computer_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quesgrouprecord',
            name='coop_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(0), related_name='Ques_coopUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quesgrouprecord',
            name='record_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quesgrouprecord',
            name='teacher_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quesgrouprecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(0), related_name='Ques_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sightsingingrecord',
            name='alignment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sightsingingrecord',
            name='chord',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sightsingingrecord',
            name='computer_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sightsingingrecord',
            name='coop_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(0), related_name='sightsinging_coopUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sightsingingrecord',
            name='fluency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sightsingingrecord',
            name='merge_audio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sightsingingrecord',
            name='pitch',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sightsingingrecord',
            name='ques_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sightsingingrecord',
            name='rhythm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sightsingingrecord',
            name='speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sightsingingrecord',
            name='teacher_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sightsingingrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(0), related_name='sightsinging_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sightsingingrecord',
            name='vice_audio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
