# Generated by Django 3.2.13 on 2022-07-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='nickname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
