# Generated by Django 3.2.13 on 2022-07-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_notice_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatar/%Y%m%d'),
        ),
    ]
