# Generated by Django 3.2.13 on 2022-07-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_notice_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='avatar',
            field=models.TextField(null=True),
        ),
    ]
