# Generated by Django 3.2.13 on 2024-04-09 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_alter_notice_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name': '通知表单', 'verbose_name_plural': '通知表单'},
        ),
    ]
