# Generated by Django 3.2.13 on 2022-07-07 17:33

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=50)),
                ('classroom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(null=True, on_delete=models.SET(0), related_name='teacher_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.ImageField(upload_to='avatar/%Y%m%d')),
                ('class_id', models.ForeignKey(null=True, on_delete=models.SET(0), related_name='student_class', to='user.class')),
                ('course_id', models.ManyToManyField(null=True, related_name='student_course', to='user.Course')),
                ('user_id', models.ForeignKey(null=True, on_delete=models.SET(0), related_name='student_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_id',
            field=models.ForeignKey(null=True, on_delete=models.SET(0), related_name='course_teacher', to='user.teacher'),
        ),
    ]
