# Generated by Django 3.2.13 on 2022-07-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220708_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigIntegerField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
