# Generated by Django 3.2.13 on 2022-07-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220708_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='metronome',
            field=models.BooleanField(default=False),
        ),
    ]
