# Generated by Django 3.2.13 on 2022-07-12 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_student_metronome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='rank',
            new_name='grade',
        ),
    ]
