# Generated by Django 3.2.13 on 2022-08-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_rank_course_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.TextField(null=True),
        ),
    ]
