# Generated by Django 3.2.13 on 2022-10-18 14:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0007_alter_student_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(0), related_name='student_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
