# Generated by Django 3.2.13 on 2022-10-21 11:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0008_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(0), related_name='teacher_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
