# Generated by Django 3.2.13 on 2022-10-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
