# Generated by Django 3.2.13 on 2022-11-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_teacher_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=models.SET(0), related_name='class_teacher', to='user.teacher'),
        ),
    ]
