# Generated by Django 3.2.13 on 2022-11-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_class_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='course',
            field=models.ForeignKey(null=True, on_delete=models.SET(0), related_name='class_course', to='user.course'),
        ),
    ]
