# Generated by Django 3.2.13 on 2024-04-16 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_class_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': '班级表', 'verbose_name_plural': '班级表'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '课程表', 'verbose_name_plural': '课程表'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学生表', 'verbose_name_plural': '学生表'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '教师表', 'verbose_name_plural': '教师表'},
        ),
    ]
