# Generated by Django 3.2.13 on 2024-01-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('opening_time', models.DateField(auto_now_add=True)),
                ('lesson_1', models.BooleanField(default=False)),
                ('lesson_2', models.BooleanField(default=False)),
                ('lesson_3', models.BooleanField(default=False)),
                ('lesson_4', models.BooleanField(default=False)),
                ('lesson_5', models.BooleanField(default=False)),
                ('lesson_6', models.BooleanField(default=False)),
                ('lesson_7', models.BooleanField(default=False)),
                ('lesson_8', models.BooleanField(default=False)),
            ],
        ),
    ]
