# Generated by Django 3.2.13 on 2024-01-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseconfig',
            name='opening_time',
            field=models.DateTimeField(),
        ),
    ]
