# Generated by Django 3.2.13 on 2024-01-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_courseconfig_opening_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseconfig',
            name='opening_time',
            field=models.DateField(),
        ),
    ]
