# Generated by Django 3.2.13 on 2024-04-09 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_courseconfig_opening_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseconfig',
            options={'verbose_name': '系统配置表', 'verbose_name_plural': '系统配置表'},
        ),
    ]
